### ISSUE TITLE
Problem when building using Gatsby.js

### ISSUE THREAD

**Issue by jvanhare** [FormidableLabs/spectacle#1004]
Hello everyone,

### Describe Your Environment

spectacle@7.1.3
react@16.14.0
Chrome Version 89.0.4389.90
macOS Big Sur Version 11.2.3 (20D91) 

### Describe the Problem

First of all, thank you very much for the great job you are doing with Spectacle.
I am using it to create my own template for my scientific presentations.
I have done a repository https://github.com/jvanhare/slides to help you to reproduce my problem.
I have integrated it with Gatsby.js.
When I do _yarn start_, I get the expected result.
However, when I do _yarn build_ to deploy it on GitHub pages, I obtain the following error:

_success Building HTML renderer - 8.324s
failed Building static HTML for pages - 0.375s

 ERROR #95312

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html

  25 | var noop = function noop() {};
  26 |
> 27 | var BroadcastChannel = window.BroadcastChannel || BroadcastChannelPolyfill;
     | ^
  28 | export default function useBroadcastChannel(channelName) {
  29 |   var onMessage = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : noop;
  30 |   var deps = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : [];

  WebpackError: ReferenceError: window is not defined

  - use-broadcast-channel.js:27
    [slides_gatsby]/[spectacle]/es/hooks/use-broadcast-channel.js:27:1_

The error message suggests that the problem comes from the fact that spectacle is using a window which is not defined when building the static html.
What am I doing wrong?
I am definitely not a very experienced react developer!
Do you any idea to solve this problem?

Thank you in advance,
Cheers,
Julien

**Comment by gksander** [comment]
Hi @jvanhare - it sounds like you're on the right track! Spectacle uses some browser APIs that are not available in Node (including references to the `window` object). I'm assuming that when Gatsby tries to build your site to static HTML (which happens in Node), it's stumbling on these browser-APIs (because they aren't available during the build process). Gatsby's documentation has a few suggestions for this: [see this page on their docs site](https://www.gatsbyjs.com/docs/using-client-side-only-packages/). There are a few approaches here. One option might be to use (using `loadable-components`), wrap each presentation into its own component, and then when you want to use a presentation - use `loadable-components` to lazily load in that presentation. This approach entails not rendering the presentation to HTML during Gatsby's build process, and then lazily loading in the assets (including Spectacle) only in the web browser.

**Comment by jvanhare** [comment]
Hi @gksander

Thank you so much for your help!
I followed your recommendation and used loadable-components in order to solve my problem.
I simply tried to convert the following code, which works as expected:

```javascript
import {Deck, Slide} from 'spectacle'
const IndexPage = () => {
  return (
    <Deck>
      <Slide>
        <div>Test</div>
      </Slide>
    </Deck>
 )
}
export default IndexPage
```

 with loadable-components:

```javascript
import loadable from '@loadable/component'
const Deck = loadable(() => import('spectacle'), {
  resolveComponent: (components) => components.Deck,
})
const Slide = loadable(() => import('spectacle'), {
  resolveComponent: (components) => components.Slide,
})const IndexPage = () => {
  return (
    <Deck>
      <Slide>
        <div>Test</div>
      </Slide>
    </Deck>
 )
}
export default IndexPage
```

No error when I run gatsby build but nothing is displayed.
Again, what am I doing wrong?
Again, thanks for your help.

Julien

**Comment by gksander** [comment]
If I can free up some time, I'll try out the sample code you attached. In the meantime, I'm curious what the motivation for using Gatsby is. Do you plan to add additional static content to the site (and the slides are just part of a larger site)? If your site consists of strictly the slides, you might consider using a different tool that is not geared toward static site generation - such as Spectacle's own CLI tools, or even Create React App - so that you don't have to fight as much with the build process.

**Comment by jvanhare** [comment]
Yes, you are right @gksander! I was simply used to Gatsby because I created my personal website with it. The site only consists of the slides and then I deploy using GitHub pages and then I simply redirect from my website to these slides.
So, to answer your question, I give up trying to use Gatsby and simply use the Spectacle's CLI tools and of course, no more problem! Thank you so much for your time and your answers! I think we can close the issue. Thanks again!

**Comment by gksander** [comment]
Happy to help! Glad you got it figured out.
