### ISSUE TITLE
Alias [space] and Shift+[space] to next & prev, respectively

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#128]
^

**Comment by kenwheeler** [comment]
Or would this interfere with typing while in an interactive slide w/ input?

**Comment by kenwheeler** [comment]
Any thoughts on how to handle that scenario? I could check the event target...

**Comment by ryan-roemer** [comment]
@kenwheeler -- For interactive code editing, I think the best bet is disable everything / almost everything (but escape) for navigation while focused and in the demo... For our other training stuff this is easier because we have a modal pop, so state management is separate from the slide deck (that deck / system is reveal-based).

HTH!

**Comment by kenwheeler** [comment]
@ryan-roemer good call. Updated to check for input.
