### ISSUE TITLE
[Feature Request] - Markdown stylesheet

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#146]
Add a prop (`style`?) to a Markdown tag that will generate a scoped style tag that will apply to the generated elements.

cc @ryan-roemer

**Comment by kenwheeler** [comment]
Alternatively, use tag naming to access style object keys and pass the values on to generated component tags

**Comment by kenwheeler** [comment]
@ryan-roemer proposing an API for this:

```
<Markdown
    propOverrides={{
         h1: {
             fit: true
         },
         p: {
            style: { margin: 20 }
         }
    }}
/>
```

^ Using this method would allow us to predefine props to be passed onto supported markdown element. Thoughts?

**Comment by ryan-roemer** [comment]
LGTM. But, I'm fine with the first-class React component overrides instead if that makes more sense from an API perspective...

@jjt -- Any thoughts?

**Comment by kenwheeler** [comment]
The advantage in my mind is the addition of layout props like `fit` in as well as style overrides

**Comment by jjt** [comment]
I like @kenwheeler's example from an API standpoint. Should cover 99% of the use cases for Markdown props/styling.

For the people who really need first class component overrides, they could pass in a different [`mdastConfig`](https://github.com/FormidableLabs/spectacle/blob/master/src/components/markdown.js#L77) prop. Though it is currently up to the user to merge the defaults object with their customization, and it's a bit wonky because of how mdast works (see the `spectacleComponent` function). Would probably want to clean that up and expose a better API.

**Comment by Hunter-Github** [comment]
I don't get the need for all this react-ful awesomeness when there is [remark](https://github.com/gnab/remark).

**Comment by kenwheeler** [comment]
Remark doesn't seem to be nearly as feature rich or extensible. Spectacle's core value is derived from the ability to embed interactive React components into your slideshow. Also, if you work primarily in react, writing your presentation in JSX is also nice. The option to write markdown is there for convenience, but markdown isn't nearly expressive enough for a lot of the interactions that I require in a typical presentation.
