### ISSUE TITLE
Responsive design with media queries

### ISSUE THREAD

**Issue by sidsarasvati** [FormidableLabs/spectacle#172]
I was browsing through the code base to learn about abstracting responsive/resizing behavior of components with css-in-jss. I see that the project uses Radium however it does use media queries but instead registers to windows.resize event for recalculate relative sizes of rendered component. Can some throw some light on some of this design decision?

**Comment by kenwheeler** [comment]
Scaling in spectacle is an interesting challenge. I look at it as adaptive vs responsive design. I think of adaptive design as, the page snaps to a new layout/sizing at certain breakpoints. This is where media queries are helpful. For spectacle however, you want a smooth scaling responsive approach. While this can be generally achieved with clever relative units, it doesn't account for mobile or height. The spectacle scaling system is set up like this:

Your base content area is 1000px x 700px. If you go below that, in width or height, it begins to scale the content using css transforms. In fact, it takes the min from height vs width and scales to that, so that visual consistency remains. 

This does present an issue on mobile though. On mobile, there is special logic that width fits the content area and doesn't let it drop below a certain size. This is so that text and context remain legible on phones, providing presentation creators adhere to em/rem units and plan for a responsive preso.

Check out this gif here, I devtool'd the content area to be yellow so you can see how it rolls:

![scaling](https://cloud.githubusercontent.com/assets/286616/15132494/58e674d0-1628-11e6-9d91-9e0b3292f6f3.gif)

**Comment by sidsarasvati** [comment]
Thanks for the explanation.
