### ISSUE TITLE
Neutral default theme

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#234]
The current theme is a bit loud. A better default would be something more subtle and universal, that can be built upon.

**Comment by JonathanCooperD** [comment]
After digging into this issue, it appears Redux is pretty deeply integrated into the app. In order to strip it out it will require some pretty heavy rewriting. I am a bit reluctant to go down that path unless future updates will never require any of the features Redux has to offer. Let me know what you think.

**Comment by JonathanCooperD** [comment]
A PR has been submitted addressing the new theme.
