### ISSUE TITLE
Separate into npm installable library

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#27]
Separate library into core, npm installable library and a separate boilerplate project

**Comment by fru** [comment]
+1

**Comment by ryan-roemer** [comment]
@kenwheeler -- I've got a working POC using just a raw `git+https` dependency on `spectacle` that builds at this snapshot https://github.com/ryan-roemer/surge2015/tree/533937a17eea75c2ae092fe019ca6d6c83b3bd2b

I think this ticket really isn't that far off, and it's really just a matter of perhaps removing deps from _this_ repo and making them required in the upstream implementing repo (or whatever the official replacement for `peerDependencies` is now that they're deprecated).

At any rate, hope this helps!

**Comment by kenwheeler** [comment]
Oh wow, @ryan-roemer  thats awesome. Gonna have a look at this for the next release.

**Comment by Spy-Seth** [comment]
This is a must to have feature :+1:

**Comment by firstdoit** [comment]
This! Do you guys need help? What if we had a repo called `spectacle-core` as suggested by #69? 

Upgradeability, easier to have lots of presentations on the same repo, etc.

**Comment by firstdoit** [comment]
Is someone working on this, or is a PR welcome?

**Comment by kenwheeler** [comment]
How would you set it up? Trying to get the 0.14 update merged as the first order of business.

**Comment by firstdoit** [comment]
I'm currently using the approach in https://github.com/ryan-roemer/surge2015. 
However, I think the correct metaphor would be to "just work" with a default `index.jsx` instead of having that boilerplate on the root of my project. Also, instead of having a `themes/theme-name` folder, we should have a `theme/` folder from where it's picked up automatically. Finally, `presentation/deck.jsx` could be `presentation/index.jsx`, because that's where we'd expect the presentation to begin, I guess.
At least for me, that would be the ideal setup :) :dancer:

**Comment by firstdoit** [comment]
Oh, and porting it to https://github.com/gaearon/react-transform-boilerplate would be awesome.

**Comment by kenwheeler** [comment]
Yeah thats up next after the 0.14 update. I figure we could split it into two parts, a core npm library, and a boilerplate that comes with a theme. thoughts?

**Comment by firstdoit** [comment]
Splitting it is a requirement either way, so I'm all for that! Then we will be able to see better how much boilerplate we need on the "client" repo. :)
Happy to know you're working on it!

**Comment by kenwheeler** [comment]
npm installable `spectacle@1.0.0-rc1`. Boilerplate project forthcoming.

**Comment by firstdoit** [comment]
:tada: great work!
