### ISSUE TITLE
Support style on every component

### ISSUE THREAD

**Issue by AndersDJohnson** [FormidableLabs/spectacle#403]
We should allow use of native React `style` prop on every component. It should forward on those styles to the underlying elements. This is useful in many cases to tweak the style of the components where the built-in props are insufficient.

**Comment by philpl** [comment]
Most components do accept the style prop and use it with emotion to add it to dynamic styles. In cases where that’s not supported the theme would also be a place to modify styling.

But are there any components in particular, that you’ve noticed, that do not accept the style prop. Unfortunately it would take a while to go through all of them otherwise 😅

**Comment by kenwheeler** [comment]
In the 4.0 release every component should have this functionality. If you notice a specific one doesn't let me know and i'll reopen.
