### ISSUE TITLE
Bug: Security warning from upstream `surge` bug from transitive dep on old `tar`.

### ISSUE THREAD

**Issue by interglobalmedia** [FormidableLabs/spectacle#423]
## Tasks

- [ ] Update `surge` dependency in `package.json` once https://github.com/sintaxi/surge/issues/293 is resolved.

## Original Issue Description

The warning here on Github:

```
We found a potential security vulnerability in one of your dependencies.
The tar dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 2.0.0 and should be updated.

Only users who have been granted access to vulnerability alerts for this repository can see this message.
Learn more about vulnerability alerts

npm / node-tar tar Known security vulnerability
```

FYI

**Comment by interglobalmedia** [comment]
And then, I removed dist from .gitignore to see what would happen and then re-deployed. Then tried out the link I was given for Surge, and I was directed to a youtube video??? This is the link: [](https://www.youtube.com/watch?v=dQw4w9WgXcQ). Not good. I have an important presentation, and this is not working well.

**Comment by ryan-roemer** [comment]
@interglobalmedia -- I have no idea what's up with the rickroll video. I'm guessing it's something to do with surge.sh on their side. Feel free to open up a separate issue with your repo + deploy steps you're taking and I'll see if I can reproduce the same thing on my end and dig in.

I dug into that ancient `tar` thing and it's from the `surge` package:

```
surge@latest:
  version "0.18.0"
  resolved "https://registry.yarnpkg.com/surge/-/surge-0.18.0.tgz#1c4378c7a5204b96f45eeaf29bfa117a19995ce9"
  dependencies:
    du "0.1.0"
    fstream-ignore "1.0.2"
    is-domain "0.0.1"
    minimist "1.1.1"
    moniker "0.1.2"
    netrc "0.1.4"
    progress "1.1.8"
    prompt "~0.2.14"
    read "1.0.5"
    request "2.40.0"
    split "0.3.1"
    surge-ignore "0.2.0"
    tar "1.0.0"
    tar.gz "0.1.1"
    url-parse-as-address "1.0.0"

tar.gz@0.1.1:
  version "0.1.1"
  resolved "https://registry.yarnpkg.com/tar.gz/-/tar.gz-0.1.1.tgz#e914ce23b2fdc627575fbdb3485a5b228ed59947"
  dependencies:
    commander "1.1.x"
    fstream "0.1.x"
    tar "0.1.x"

tar@0.1.x:
  version "0.1.20"
  resolved "https://registry.yarnpkg.com/tar/-/tar-0.1.20.tgz#42940bae5b5f22c74483699126f9f3f27449cb13"
  dependencies:
    block-stream "*"
    fstream "~0.1.28"
    inherits "2"
```

Which still has the `tar.gz` package dep at `0.1.1`. https://github.com/sintaxi/surge/blob/master/package.json#L19

Unfortunately, that project is deprecated https://github.com/alanhoff/node-tar.gz which means that's why `tar@0.1.x` is there and why it won't get updated. There is already an upstream issue on the `surge` repo at https://github.com/sintaxi/surge/issues/293 so I'm going to slightly adjust your original description with the action item of "update surge once 293 is resolved".

Thanks for reporting the error on our side -- we definitely want to keep on top of these things!

**Comment by interglobalmedia** [comment]
Yeah it is. Ken figured that out last night and I removed the dep, pushed the changes to remote, and then my warnings were gone. And even tho the warnings highlighted versions < 2, the version in package-lock.json was 2.2.1. So that was strange! Surge has been wonky of late, at least for me anyway. I have seen issues pop up here and there about it. I don't have time now, but will try and come up with a solution for deploying (somewhere). You don't want to know how I deployed after removing Surge lol. There just was no time for a good fix.
