### ISSUE TITLE
styled-components styles are being overwritten

### ISSUE THREAD

**Issue by himynameisdave** [FormidableLabs/spectacle#426]
Hi, I am working on a presentation and am trying to create styled `Heading`s using `styled-components`, [exactly as outlined in the FAQ](https://github.com/FormidableLabs/spectacle#faq):

```js
import React from 'react';
import styled from 'styled-components';
import {
    Heading,
    Slide,
} from 'spectacle';


const SlideTitleCard = ({ title, }) => {
    const StyledHeading = styled(Heading)`
        font-size: 1.2em;
        color: papayawhip;
    `;
    return (
        <Slide
            transition={['zoom']}
            bgColor="primary"
            align="flex-start"
        >
            <StyledHeading>
                {title}
            </StyledHeading>
        </Slide>
    );
};
```

But when I run the app in the browser, I see that the default `Heading` styles are overriding my custom `styled` CSS:

![image](https://user-images.githubusercontent.com/4298089/32986558-a582e418-cc89-11e7-8a3e-2c90baa72055.png)

Seems like I am doing something dumb, what am I missing here?

**Comment by philpl** [comment]
Hm, unfortunately I think that the order of style tags in your head tag is reversed. Right now there’s no solution for SC to work around that apart from using SSR.

If you wrap your styles inside the styled component in “& { ... }” that will add the class twice around your styles, thus increasing specificity.

Sorry, I’m not sure how to solve it in a more sensible way right now, but we’re working on a Stylesheet provider over at SC for this exact problem.

You could also try out emotion, since the API is quite similar

**Comment by prayasht** [comment]
@kitten Could you give a more detailed example? I tried this and it's still being overwritten by the default styles. Such a bummer that it's not possible to write a stylesheet on top like most CSS things.
```
const CustomHeading = styled(Heading)`
  & {
    font-size: 1.2em;
    font-weight: 200;
  }
`
```

**Comment by kitten** [comment]
@prayasht do you have time to create a little reproduction on CodeSandbox or sth similar? That should give me an environment to find a solution in combination with emotion
