### ISSUE TITLE
Markdown Table seems to be broken

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [FormidableLabs/spectacle#429]
Markdown table seems to be broken, can you help me what is going wrong in this format? I don't see it is working correctly, Attached image, how it appears on my screen. 

```
<Slide transition={['spin', 'zoom']} bgColor="tertiary" controlColor="primary" progressColor="primary">
          <Markdown>
            {`
  | Tables        | Are           | Cool  |
  | ------------- |:-------------:| -----:|
  | col 3 is      | right-aligned | $1600 |
  | col 2 is      | centered      |   $12 |
  | zebra stripes | are neat      |    $1 |  
            `}
          </Markdown>
        </Slide>
```

<img width="714" alt="screen shot 2017-11-20 at 9 48 36 am" src="https://user-images.githubusercontent.com/354710/33002117-0b4ba02e-cdd8-11e7-80fd-e16eadf21403.png">

**Comment by kale-stew** [comment]
I was able to produce a successful markdown table with your sample code, so it's possible this issue is occurring somewhere else in your project or was patched in a recent update. 

Your code (only changed to be wrapped in an unadulterated set of `<Deck>` tags):
```
render() {
    return (
      <Deck>
        <Slide transition={['spin', 'zoom']} bgColor="tertiary" controlColor="primary" progressColor="primary">
          <Markdown>
              {`
  | Tables        | Are           | Cool  |
  | ------------- |:-------------:| -----:|
  | col 3 is      | right-aligned | $1600 |
  | col 2 is      | centered      |   $12 |
  | zebra stripes | are neat      |    $1 |  
              `}
          </Markdown>
        </Slide>
      </Deck>
    );
  }
```

renders this:
<img width="688" alt="screen shot 2018-02-05 at 3 57 32 pm" src="https://user-images.githubusercontent.com/30479228/35833333-edfa4dc0-0a8d-11e8-85dd-0daa45cd7b47.png">

If you are still having trouble with this issue in your project, feel free to reopen with updated context. 🙂
