### ISSUE TITLE
Markdown Tag

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#43]
It would be a very useful addition to have something like

```jsx
<Markdown source={require("raw!./testmd.md")} />
```

or/and

```jsx
<Markdown>#Heading 1
some text

* item 1
* item2
</Markdown>
```

I prototyped the first example using marked and katex for math. However, I do need to adjust the styles.

I could not get the second example working. I am a novice in terms of react and I have no idea how I can access the inner text as a raw string with the line breaks. ```this.props.children``` only returns a string without line breaks.

**Comment by ryan-roemer** [comment]
Cool idea! Could maybe even just import https://github.com/acdlite/react-remarkable directly as an "out of band" solution (or something like it).

**Comment by waywaaard** [comment]
The problem with most react-markdown libraries is that they just output the generated HTML and just use ```dangerouslySetInnerHTML```. This does not allow the styling that we would apply otherwise with Radium and the spectacle tags.

**Comment by ryan-roemer** [comment]
Ah, sounds like I need to leave it to the experts!

![](http://i.imgur.com/tZOS8.gif)

**Comment by waywaaard** [comment]
I've tried to implement the dynamic creation of the slide from a markdown source.

See: https://github.com/waywaaard/spectacle/blob/markdown/presentation/markdownspectacle.jsx

However, it is not working because my dynamically created elements like ```<Heading>``` do not receive the same ```context``` as the other elements of the type.

I get the following error that holds me back:

> Uncaught TypeError: Cannot read property 'components' of undefined heading.jsx:100

**Comment by kenwheeler** [comment]
I'll look into this, but the reason I use Heading tags instead of free form HTML is to provide that context. For this to work I would have to parse the markdown and generate Spectacle tags based upon the syntax

**Comment by waywaaard** [comment]
That is what I was trying to do. I am also not sure where ```src\utils\context``` is actually used.

**Comment by bebraw** [comment]
FYI [markdown-to-react-components](https://github.com/christianalfoni/markdown-to-react-components) produces real React components based on Markdown. I actually found a little bug in it but for the most part it seems better than most of the libraries out there.

**Comment by kenwheeler** [comment]
@bebraw great find, going to look into this

**Comment by waywaaard** [comment]
That's basically what I am doing :P in my repo

**Comment by bebraw** [comment]
I thought about this further. If we had `SlideSets` (#57), we could do something like this:

**demo.slideset**

```
# Demo Section
---
* Awesome
* Section
* Magix
---
> Design is awesome - John Doe
---
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
---
# Two
## Headers
```

This markdownish syntax could then be converted to a `SlideSet` through a Webpack loader. You would do something like `import slideSet from './demo.slideset';`. The loader would then parse the custom syntax and convert it to React elements spectacle expects.

The only potential problem is that if you author a `SlideSet` this way, it doesn't allow a lot of customization. If you need something totally custom, you still need to write JSX. Perhaps there could be an import statement to work around this? You would do something like `require('./interactive.jsx')` within our syntax. Then we would resolve that through Webpack as usual.

I think something like this would make it more fun to author slides with spectacle as you could focus on the slide contents instead of JSX, transitions and such. Ideally you should still have some level of control over transitions, though, but I believe it may be better to deal with that through configuration by default. We can also do custom syntax to match JSX perfectly.

**Comment by ryan-roemer** [comment]
In case it helps, how I'd like to use markdown when authoring would be scenarios of mixed / pure MD usage within a slide:

```
<Slide>
  <Markdown>
    ## Hello MD Heading

    * One
    * Two 
    * Three
  </Markdown>
</Slide>
<Slide>
  <Heading size={1} caps fit>
    React Heading
  </Heading>
  <Markdown>
    * One
    * Two 
    * Three
  </Markdown>
</Slide>
```

**Comment by kenwheeler** [comment]
@ryan-roemer that's how I invision the implementation would look like.

**Comment by bebraw** [comment]
@ryan-roemer I would be happy with that esp. if we get #57. I feel that would help a lot with big presentations. :+1:

**Comment by jjt** [comment]
I did some investigating with markdown-to-react-components, and knocked together something usable here: https://github.com/jjt/spectacle/pull/1. It works from a user-facing perspective, but the implementation is cludgy.

A better approach might use [mdast](https://github.com/wooorm/mdast) and [mdast-react](https://github.com/mapbox/mdast-react), or a custom mdast plugin based on mdast-react.

**Comment by jjt** [comment]
Made some more progress toward this, and I've got markdown rendering to Spectacle elements for headings (1-6), paragraphs, links, strikethrough/italic/bold text, images, and lists. The <Markdown> component accepts a source prop or inline contents.

Blockquotes are a bit weird right now because markdown-to-react-components (MTRC) wraps the content in a `<p>`, and it ends up rendering comically large.

I couldn't find an interface for codeblock from MTRC, so code doesn't work either at the moment.

```js
       <Slide>
          <Markdown>
            {`
#### Markdown text, inline
##### Sub-heading
[Bacon ipsum](http://baconipsum.com) dolor amet jerky t-bone fatback, pork alcatra beef ribs bresaola swine pancetta rump shank kielbasa.
* List
* ~~Prosciutto~~ shankle _sirloin_
* Tenderloin **doner** short ribs
            `}
          </Markdown>
        </Slide>
        <Slide>
          <Markdown source={require("raw!./markdown-image.md")}/>
        </Slide>
        <Slide>
          <Markdown source={require("raw!./markdown-blockquote.md")}/>
        </Slide>
```


![image](https://cloud.githubusercontent.com/assets/399469/10359485/004dfa7e-6d4e-11e5-980e-319d1b00dfe4.png)

![image](https://cloud.githubusercontent.com/assets/399469/10359494/0e08bec4-6d4e-11e5-8327-f052a49ee7a2.png)

![image](https://cloud.githubusercontent.com/assets/399469/10359500/184e46e2-6d4e-11e5-9dc5-dedd04a62cc0.png)

**Comment by kenwheeler** [comment]
Whoah that looks great

**Comment by jjt** [comment]
Thx! If you could see this in Spectacle (instead of userland), I can start a PR and we can go from there.

Need to tackle blockquoting and code issues, figure out a good user config story, and clean up the implementation.

**Comment by kenwheeler** [comment]
Totally
