### ISSUE TITLE
How to embed the presentation?

### ISSUE THREAD

**Issue by hyunwoona** [FormidableLabs/spectacle#441]
I am trying to embed the presentation in a `div` that does not take up the whole browser viewport.

I tried to set the width and the height of the `Deck` like so

```
const CustomDeck = styled(Deck)`
   width: 700px;
   height: 500px;
`;
```

but it fails.

How can I do this?

**Comment by aravindballa** [comment]
I too tried this once. Couldn't make it work. Probably height and width of `html, body` are set to 100%.

My workaround was to embed this in an `iframe`.

**Comment by philpl** [comment]
The exported `Deck` component renders three other components and passes most props on to the `Manager`. But unfortunately currently the `StyledDeck` there doesn't accept additional `className`s: https://github.com/FormidableLabs/spectacle/blob/master/src/components/manager.js#L39-L50

However, since it utilises `position: absolute` you should be able to just wrap the entire `Deck` component in a `position: relative` container. I haven't tried this before but it might be worth a shot :wink:

**Comment by chrisheninger** [comment]
Wrapping with `position: relative` works nicely– the only other adjustment I found I had to make was add a `body {  overflow-y: auto !important; }` to cancel out the overflow:hidden; applied by Spectacle.

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
