### ISSUE TITLE
<Appear /> + Emotion styled component = many style tags

### ISSUE THREAD

**Issue by elifitch** [FormidableLabs/spectacle#488]
Every time an `<Appear />` tag executes a tween, it looks like emotion is adding a bunch of style tags to the head.

![mar-17-2018 17-38-30](https://user-images.githubusercontent.com/2495933/37560172-16d3a20a-2a0a-11e8-8c08-2cc71e19c553.gif)

Wrapping the children of an `<Appear />` in a native dom element seems to be a pretty solid workaround, but should probably be noted somewhere in the documentation until this issue is resolved.

I'm working on a PR to Spectacle which would allow more flexible animations, and I'd be happy to add a note to the docs along with my PR if you'd like.

**Comment by kitten** [comment]
I think the problem here is quite simple. Spectacle's Appear component is right now just passing on a `style` prop;

https://github.com/FormidableLabs/spectacle/blob/master/src/components/appear.js#L81

Now unfortunately some components take that `style` prop and are interpolating it into emotion, which then considers it part of its styles, which means that it'll be mounted into the style tag. 

https://github.com/FormidableLabs/spectacle/blob/master/src/components/text.js#L99-L103

Now, this is not a horrible thing to do, but it'll definitely constrict the performance, as it'd be much faster to in this case just use the normal React `style` prop, which I'd consider a best practice for both emotion and styled-components.

cc @kenwheeler: Any thoughts? Would this be a pain to change?

**Comment by kenwheeler** [comment]
Does this happen in prod as well as dev?

**Comment by kale-stew** [comment]
Closing for lack of response from the OP
