### ISSUE TITLE
prism plugins

### ISSUE THREAD

**Issue by sag1v** [FormidableLabs/spectacle#618]
### Question

I'm sure i am missing something and it seems easy but for some reason i struggle with this. 
I would like to use couple of prism plugins ([line-numbers](https://prismjs.com/plugins/line-numbers/) and [line-highlight](https://prismjs.com/plugins/line-highlight/)) and i have tried couple of things but no luck so far.  

### Background Info/Attempts

I'm using the [spectacle-boilerplate](https://github.com/FormidableLabs/spectacle-boilerplate).
I have tried to import the appropriate files:

Let's focus on `line-numbers`:
```
import 'prismjs/plugins/line-numbers/prism-line-numbers.css';
import 'prismjs/plugins/line-numbers/prism-line-numbers.js';
```
Then i have added the `CSS` class `line-numbers` (as per the [docs](https://prismjs.com/plugins/line-numbers/#how-to-use))

```
<CodePane
  className="line-numbers"
  textSize={'1.5em'}
  lang="javascript"
  source={check}
/>
```

And i do see the `<pre>` tag with this class (although it seems that `CodePane` is injecting it to the wrapping `div` as well).

I also see the the styling:  
![image](https://user-images.githubusercontent.com/9153149/49399194-4c534900-f749-11e8-8a98-9ec3e3e124d7.png)

But when i look at the actual styling i see it targets some classes that are not there
![image](https://user-images.githubusercontent.com/9153149/49399358-bec42900-f749-11e8-940d-642ea965ee02.png)

That makes me think maybe the js file is not really imported (maybe its because it got excluded in the web.config?)

I also tried to use [babel-plugin-prismjs](https://www.npmjs.com/package/babel-plugin-prismjs) with no luck. but i honestly not sure this is the way to go, it was just a poor attempt.

**Comment by kitten** [comment]
If I'm correct this plugin requires some additional markup, like `line-numbers-rows`, which shouldn't be too hard to add? Its JS file might attempt to add this code by targeting specific other classes that we are not setting on the codepane. This was an older, conscious decision in this project, and also in `react-live`.

This is because modifying the DOM that React controls can sometimes be a bad idea, unless its encapsulated in a component of its own. So it's definitely possible, but a little fiddly.

Instead, as we've posted on Twitter, prism-react-renderer might be a project worth checking out, if you want to create a highly customised component for rendering your code, including additional bits like line numbering. https://github.com/FormidableLabs/prism-react-renderer

In fact for `mdx-deck` [there's already sth that does this](https://github.com/pomber/code-surfer) so this could also be ported to Spectacle in theory

**Comment by sag1v** [comment]
Yeah i have looked at `prism-react-renderer` and its flexible as hell, though i'm not sure it will help me, i mean it can help but there is a lot of work to do in order to achieve something that is already built in for prism.  

As for `code-surfer` , this is  an amazing abstraction and a great tool, but again this is not what i'm looking for.

I'm actually trying to do something similar to [this presentation i made before](https://sag1v.github.io/Async-Javascript-Presentation/) but with `react` and `mdx` instead of `remarkjs`.

I don't want the code box to take most of the screen and i would like to keep it simple, it seems that `code-surfer` is a bit too much for my current needs.
`Spectacle` on the other hand with its `CodePane` component, seems just what i need. but i'll have to think how to get around the lines highlights and numbering. or maybe just live without it :man_shrugging: 

Thanks for the help though @kitten! :+1:  :heart:
