### ISSUE TITLE
Package TypeScript Type definitions locally

### ISSUE THREAD

**Issue by rawrmonstar** [FormidableLabs/spectacle#627]
### Description

If we want to treat TypeScript as a first class citizen and require all changes to update the definitions it would probably be best to package the definitions in this repo instead of relying on DefinitelyTyped. It seems a little difficult to try to coordinate PRs to spectacle with type definition updates in a different repo.

### Proposal

I think we should maintain the type definitions in this Spectacle repo instead of DefinitelyTyped

### Links / References

An example of things being a little weird are trying to coordinate a API change in my Spectacle PR here: https://github.com/FormidableLabs/spectacle/pull/626 and the type definitions with the DefinitelyTyped PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31599

**Comment by kale-stew** [comment]
For context: I initially opted to keep our type definitions in DefinitelyTyped because

1- they were already there and broken, so it seemed more maintainable to just update them
2- the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) recommend publishing type defs to DT instead of colocating them with the package _if the library is not written in TS_. Honestly, I do not understand the reasoning behind this and would be open to removing the type defs from DT and shipping them with the library so long as there is no adverse side effect from doing so

**Comment by kale-stew** [comment]
The above being said, I agree that updating the defs separately from introducing the feature is a rough process and, since a bot handles merging DefinitelyTyped's PRs, there's potential for type defs to merge without the feature itself. This could get ugly quick

**Comment by rawrmonstar** [comment]
I'll do this today
