### ISSUE TITLE
Overview Mode seems to be broken

### ISSUE THREAD

**Issue by on3iro** [FormidableLabs/spectacle#888]
Sorry to bother you with another issue, but somehow the overview mode does not work as expected ;)

### Describe Your Environment

What version of Spectacle are you using? **6.0.2**

What version of React are you using? **16.13.1**

What browser are you using? **Firefox Developer Edition** / **Chrome**

What machine are you on? **Mac OSX**

### Describe the Problem
 Reproducable in the example Sandbox: [simple Spectacle sample Sandbox](https://codesandbox.io/s/simple-spectacle-example-3jebu)

**Expected behavior:**
I expect an overview to show up, when I press Alt + O (https://formidable.com/open-source/spectacle/docs/advanced-concepts/#keyboard-controls)

**Actual behavior:**
I see a black screen showing only the very last slide. No other slides are shown.

![Screenshot 2020-04-23 at 20 19 56](https://user-images.githubusercontent.com/8681413/80134982-d949ad00-859f-11ea-9812-77c7dd8b11ae.png)

**Comment by kale-stew** [comment]
No need to apologize, these issues are very helpful. 🙂

I'm thinking we introduced a regression with some of the more recent features that in turn deprecated this feature. I'll dig into this today, thanks again for bringing this to our attention!

**Comment by awareness481** [comment]
@kale-stew The issue appears to arise from the conditionals only checking for characters in uppercase. I also removed the `!!e.shiftKey` as according to my knowledge it is redundant and was also causing issues. 

I submitting a PR, noting that this was only tested and found to be working for **Windows**. I don't have the ability to test for Mac.

P.S The issue was also occurring on my Windows machine.
